require '../test/depend'
require '../test/ts_bin'
require '../test/ts_domain'
require '../test/ts_mock'
require '../test/ts_objectfield'
require '../test/ts_objectstore'
require '../test/ts_query'
require '../test/ts_schema'
require '../test/ts_test'
require '../test/ts_util'

